"""Add comments counts in table pitch

Revision ID: 0b91330d8db2
Revises: 7cd40525d0e1
Create Date: 2020-09-23 07:19:10.925219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b91330d8db2'
down_revision = '7cd40525d0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('comments_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'comments_count')
    # ### end Alembic commands ###
