"""Delete votes table.Add upvotes and downvotes column in pitches 

Revision ID: d154ba88cf87
Revises: 0b91330d8db2
Create Date: 2020-09-23 07:32:01.416702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd154ba88cf87'
down_revision = '0b91330d8db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.add_column('pitches', sa.Column('downvotes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('upvotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'upvotes')
    op.drop_column('pitches', 'downvotes')
    op.create_table('votes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vote_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], name='votes_pitch_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='votes_pkey')
    )
    # ### end Alembic commands ###
